# Generated by Django 4.2.1 on 2023-06-25 10:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangDariPemerintah',
            fields=[
                ('Id_Banpem', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_Barang', models.CharField(max_length=100)),
                ('Jumlah_Barang', models.IntegerField()),
                ('Satuan', models.CharField(max_length=100)),
                ('Tanggal', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeritaPertanian',
            fields=[
                ('Id_Berita', models.AutoField(primary_key=True, serialize=False)),
                ('Judul_Berita', models.CharField(max_length=100)),
                ('Foto_Berita', models.ImageField(blank=True, null=True, upload_to='berita/%Y/%m/%d/')),
                ('Isi_Berita', models.TextField()),
                ('Jam_Update', models.TimeField()),
                ('Tanggal_Update', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Golongan',
            fields=[
                ('Id_Golongan', models.AutoField(primary_key=True, serialize=False)),
                ('Golongan', models.CharField(default='IA', max_length=6)),
                ('Jabatan_Fungsional', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('Id_Jabatan', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_Jabatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KelompokTani',
            fields=[
                ('Id_Poktan', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_Poktan', models.CharField(max_length=25)),
                ('Kecamatan', models.CharField(max_length=30)),
                ('Desa', models.CharField(choices=[('Cidahu', 'Cidahu'), ('Balingbing', 'Balingbing'), ('Cidadap', 'Cidadap'), ('Pangsor', 'Pangsor'), ('Bendungan', 'Bendungan'), ('Munjul', 'Munjul'), ('Margahayu', 'Margahayu'), ('Mekarwangi', 'Mekarwangi')], max_length=100, null=True)),
                ('Ketua', models.CharField(max_length=25)),
                ('NIK_Ketua', models.CharField(max_length=16)),
                ('KTP_Ketua', models.ImageField(blank=True, null=True, upload_to='ktp/%Y/%m/%d/')),
                ('Sekretaris', models.CharField(max_length=25)),
                ('Bendahara', models.CharField(max_length=25)),
                ('Pemilik_Lahan', models.CharField(max_length=25, null=True)),
                ('Surat_Lahan', models.ImageField(blank=True, null=True, upload_to='surat/%Y/%m/%d/')),
                ('No_Telephone', models.CharField(max_length=13)),
                ('Komoditas', multiselectfield.db.fields.MultiSelectField(choices=[('Padi', 'Padi'), ('Palawija', 'Palawija'), ('Cabai', 'Cabai'), ('Jamur', 'Jamur'), ('Ternak', 'Ternak'), ('Sapi Potong', 'Sapi Potong'), ('KWT', 'KWT'), ('Pemuda Tani', 'Pemuda Tani')], max_length=100)),
                ('Score', models.IntegerField(null=True)),
                ('Luas_Areal_HA', models.IntegerField(null=True)),
                ('Jumlah_Anggota', models.IntegerField(null=True)),
                ('Tanggal_Pembentukan', models.DateField(blank=True)),
                ('Status_Poktan', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], max_length=100, null=True)),
                ('Kelas_Poktan', models.CharField(choices=[('Pemula', 'Pemula'), ('Lanjut', 'Lanjut'), ('Madya', 'Madya')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokoPertanian',
            fields=[
                ('Id_Toko', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_Toko', models.CharField(max_length=50)),
                ('Foto_Toko', models.ImageField(blank=True, null=True, upload_to='toko/%Y/%m/%d/')),
                ('Alamat', models.TextField()),
                ('Jam_Buka', models.TimeField()),
                ('Jam_Tutup', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UsulanBantuanPoktan',
            fields=[
                ('Id_Bantuan', models.AutoField(primary_key=True, serialize=False)),
                ('Jumlah_Bantuan', models.IntegerField()),
                ('Satuan_Bantuan', models.CharField(max_length=50)),
                ('Tanggal_Bantuan', models.DateField(blank=True)),
                ('Gambar_Lokasi', models.ImageField(blank=True, null=True, upload_to='bantuan/%Y/%m/%d/')),
                ('Status', models.CharField(choices=[('Dapat Bantuan', 'Dapat Bantuan'), ('Tidak Dapat', 'Tidak Dapat'), ('Diajukan', 'Diajukan')], max_length=100, null=True)),
                ('Id_Banpem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sitani.barangdaripemerintah')),
                ('Id_Poktan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sitani.kelompoktani')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('NIP', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=26)),
                ('Foto_Profile', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('Alamat', models.TextField()),
                ('Id_Golongan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sitani.golongan')),
                ('Id_Jabatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sitani.jabatan')),
            ],
        ),
    ]
