# Generated by Django 4.2.1 on 2023-07-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sitani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokopertanian',
            name='Deskripsi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
