# Generated by Django 4.2.1 on 2023-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sitani', '0003_beritapertanian_penulis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompoktani',
            name='Kelas_Poktan',
            field=models.CharField(choices=[('Pemula', 'Pemula'), ('Lanjut', 'Lanjut'), ('Madya', 'Madya'), ('Utama', 'Utama')], max_length=100, null=True),
        ),
    ]
