# Generated by Django 4.2.1 on 2023-07-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sitani', '0004_alter_kelompoktani_kelas_poktan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokopertanian',
            name='Nama_Pemilik',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
